name: Lighthouse Check
on:
  push:
    branches-ignore: [ "dependabot/*" ]
    paths:
      - "src/**/*.*"
      - "public/**/*.*"
      - "package*.json"
      - "*.config.*js"

  schedule:
    - cron: "0 0/6 * * *"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  URL_TO_CHECK: "https://localweather.dev"
  HTML_FILE_NAME: "lighthouse-report.html"

jobs:
  lighthouse-check:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}${{ env.HTML_FILE_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘· Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ“‚ Make tmp directory
        run: mkdir -p ${{ github.workspace }}/tmp/artifacts

      - name: ğŸƒ Run Lighthouse check
        uses: foo-software/lighthouse-check-action@master
        with:
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          urls: ${{ env.URL_TO_CHECK }}

      # this is a little hacky but we only expect one file
      - name: ğŸšš Rename report file
        run: cd ${{ github.workspace }}/tmp/artifacts && for x in *.html;do mv $x ${{env.HTML_FILE_NAME }};done

      - name: ğŸ› ï¸ Setup Pages
        uses: actions/configure-pages@v2

      - name: ğŸ—ï¸ Create and Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ github.workspace }}/tmp/artifacts

      - name: ğŸš€ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
